# Automatically generated by pb2py
# fmt: off
from .. import protobuf as p


class KlaytnMessageSignature(p.MessageType):
    MESSAGE_WIRE_TYPE = 864

    def __init__(
        self,
        signature: bytes = None,
        address: str = None,
    ) -> None:
        self.signature = signature
        self.address = address

    @classmethod
    def get_fields(cls):
        return {
            2: ('signature', p.BytesType, 0),
            3: ('address', p.UnicodeType, 0),
        }
